Rails:
  Enabled: true
Documentation:
  Enabled: false
Style/Encoding:
  Enabled: false

Metrics/AbcSize:
  Max: 33
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/LineLength:
  Max: 80
Metrics/MethodLength:
  Max: 15
Metrics/PerceivedComplexity:
  Max: 9
Metrics/CyclomaticComplexity:
  Severity: warning

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - db/schema.rb
    - 'vendor/**/*'
    - 'db/migrate/**/*'
    - 'config/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'bin/**/*'
    - 'lib/templates/**/*'

Style/HashSyntax:
  Enabled: true
Style/AccessModifierIndentation:
  Description: Check indentation of private/protected visibility modifiers.
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#indent-public-private-protected'
  Enabled: true
Style/CaseIndentation:
  Description: 'Indentation of when in a case/when/[else/]end.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#indent-when-to-case'
  Enabled: true
